In [1]:
import pandas as pd

# Import the boto3 library for interacting with AWS services
import boto3

In [2]:
#Read the data from the CSV file 'data.csv' into a pandas DataFrame and assign it to the variable 'data'
data = pd.read_csv('data.csv')
data

,Sr No.,User Name,Date,Review
0,1,John Doe,04-04-2024,The product was easy to use and arrived quickl...
1,2,Jane Smith,03-04-2024,"It does the job, but I've seen better quality ..."
2,3,Michael Lee,02-04-2024,The item arrived damaged and customer service ...
3,4,Sarah Garcia,01-04-2024,"I love the design, but the functionality is a ..."
4,5,David Kim,31-03-2024,This product exceeded my expectations! Great v...
5,6,Emily Jones,30-03-2024,It's alright. I was hoping for something a lit...
6,7,William Brown,29-03-2024,This was a complete waste of money. Do not rec...
7,8,Amanda Harris,28-03-2024,"It has some great features, but there are a fe..."
8,9,Charles Miller,27-03-2024,This is exactly what I was looking for! Perfec...
9,10,Elizabeth Johnson,26-03-2024,The product description was misleading. Disapp...

In [3]:
#This function iterated through the whole dataframe 'data', collecting them into a list 'l' and a single string 'text'. Returning
# both 'text' and 'l'
def df_function(data):
    text = ""
    l = []
    for i in range(len(data)):
        l.append(data['Review'][i])
        text = text + data['Review'][i]
    return text,l

In [4]:
#calling df_function and storing the elements it return in 'paragraph' and 'list1'
paragraph, list1 = df_function(data)

#creating a client object for the AWS Comprehend service. Make sure to enter your unique access_key and secret_key
comprehend = boto3.client('comprehend', region_name = 'us-east-1', aws_access_key_id = '--access_key--', aws_secret_access_key = '--secret_key--')
final_response = []

#iterate throught each text in 'list1'
for i in list1:
    #Perform sentiment analysis on the text using AWS Comprehend
    response = comprehend.detect_sentiment(Text = i, LanguageCode = "en")

    #Append the result to the 'final_response' list
    final_response.append(response["Sentiment"])
    

#creating a dataframe containing serial no, reviews and sentiment results
final_data = pd.DataFrame({"Sr. No": range(1, len(data['Review']) + 1),
                           'Reviews': data['Review'],
                            "Result": final_response})

In [5]:
#displaying the final result
final_data

   Sr. No                                            Reviews    Result
0       1  The product was easy to use and arrived quickl...     MIXED
1       2  It does the job, but I've seen better quality ...     MIXED
2       3  The item arrived damaged and customer service ...  NEGATIVE
3       4  I love the design, but the functionality is a ...     MIXED
4       5  This product exceeded my expectations! Great v...  POSITIVE
5       6  It's alright. I was hoping for something a lit...     MIXED
6       7  This was a complete waste of money. Do not rec...  NEGATIVE
7       8  It has some great features, but there are a fe...     MIXED
8       9  This is exactly what I was looking for! Perfec...  POSITIVE
9      10  The product description was misleading. Disapp...  NEGATIVE